package com.example.pokeguesser;

public class DexEntryDatabase {


    public static int[] pokePic = {

            R.drawable.bulbasaur,
            R.drawable.ivysaur,
            R.drawable.venusaur,
            R.drawable.charmander,
            R.drawable.charmeleon,
            R.drawable.charizard,
            R.drawable.squirtle,
            R.drawable.wartortle,
            R.drawable.blastoise,
            R.drawable.caterpie,
            R.drawable.metapod,
            R.drawable.butterfree,
            R.drawable.weedle,
            R.drawable.kakuna,
            R.drawable.beedrill,
            R.drawable.pidgey,
            R.drawable.pidgeotto,
            R.drawable.pidgeot,
            R.drawable.rattata,
            R.drawable.raticate,
            R.drawable.spearow,
            R.drawable.fearow,
            R.drawable.ekans,
            R.drawable.arbok,
            R.drawable.pikachu,
            R.drawable.raichu,
            R.drawable.sandshrew,
            R.drawable.sandslash,
            R.drawable.nidoranfemale,
            R.drawable.nidorina,
            R.drawable.nidoqueen,
            R.drawable.nidoranmale,
            R.drawable.nidorino,
            R.drawable.nidoking,
            R.drawable.clefairy,
            R.drawable.clefable,
            R.drawable.vulpix,
            R.drawable.ninetales,
            R.drawable.jigglypuff,
            R.drawable.wigglytuff,
            R.drawable.zubat,
            R.drawable.golbat,
            R.drawable.oddish,
            R.drawable.gloom,
            R.drawable.vileplume,
            R.drawable.paras,
            R.drawable.parasect,
            R.drawable.venonat,
            R.drawable.venomoth,
            R.drawable.diglett,
            R.drawable.dugtrio,
            R.drawable.meowth,
            R.drawable.persian,
            R.drawable.psyduck,
            R.drawable.golduck,
            R.drawable.mankey,
            R.drawable.primeape,
            R.drawable.growlithe,
            R.drawable.arcanine,
            R.drawable.poliwag,
            R.drawable.poliwhirl,
            R.drawable.poliwrath,
            R.drawable.abra,
            R.drawable.kadabra,
            R.drawable.alakazam,
            R.drawable.machop,
            R.drawable.machoke,
            R.drawable.machamp,
            R.drawable.bellsprout,
            R.drawable.weepinbell,
            R.drawable.victreebel,
            R.drawable.tentacool,
            R.drawable.tentacruel,
            R.drawable.geodude,
            R.drawable.graveler,
            R.drawable.golem,
            R.drawable.ponyta,
            R.drawable.rapidash,
            R.drawable.slowpoke,
            R.drawable.slowbro,
            R.drawable.magnemite,
            R.drawable.magneton,
            R.drawable.farfetchd,
            R.drawable.doduo,
            R.drawable.dodrio,
            R.drawable.seel,
            R.drawable.dewgong,
            R.drawable.grimer,
            R.drawable.muk,
            R.drawable.shellder,
            R.drawable.cloyster,
            R.drawable.gastly,
            R.drawable.haunter,
            R.drawable.gengar,
            R.drawable.onix,
            R.drawable.drowzee,
            R.drawable.hypno,
            R.drawable.krabby,
            R.drawable.kingler,
            R.drawable.voltorb,
            R.drawable.electrode,
            R.drawable.exeggcute,
            R.drawable.exeggutor,
            R.drawable.cubone,
            R.drawable.marowak,
            R.drawable.hitmonlee,
            R.drawable.hitmonchan,
            R.drawable.lickitung,
            R.drawable.koffing,
            R.drawable.weezing,
            R.drawable.rhyhorn,
            R.drawable.rhydon,
            R.drawable.chansey,
            R.drawable.tangela,
            R.drawable.kangaskhan,
            R.drawable.horsea,
            R.drawable.seadra,
            R.drawable.goldeen,
            R.drawable.seaking,
            R.drawable.staryu,
            R.drawable.starmie,
            R.drawable.mrmime,
            R.drawable.scyther,
            R.drawable.jynx,
            R.drawable.electabuzz,
            R.drawable.magmar,
            R.drawable.pinsir,
            R.drawable.tauros,
            R.drawable.magikarp,
            R.drawable.gyarados,
            R.drawable.lapras,
            R.drawable.ditto,
            R.drawable.eevee,
            R.drawable.vaporeon,
            R.drawable.jolteon,
            R.drawable.flareon,
            R.drawable.porygon,
            R.drawable.omanyte,
            R.drawable.omastar,
            R.drawable.kabuto,
            R.drawable.kabutops,
            R.drawable.aerodactyl,
            R.drawable.snorlax,
            R.drawable.articuno,
            R.drawable.zapdos,
            R.drawable.moltres,
            R.drawable.dratini,
            R.drawable.dragonair,
            R.drawable.dragonite,
            R.drawable.mewtwo,
            R.drawable.mew

    };


    public static String[] DexEntryQuestions = {

            "This Pokemon can be seen napping in bright sunlight. There is a seed on its back. By soaking up the sun's rays, the seed grows progressively larger.",
            "To support its bulb, this Pokemon's legs grow sturdy. If it spends more time lying in the sunlight, the bud will soon bloom into a large flower.",
            "There is a large flower on this Pokemon's back. The flower is said to take on vivid colors if it gets plenty of nutrition and sunlight. The flower's aroma soothes the emotions of people",
            "The flame that burns at the tip of its tail is an indication of its emotions. The flame wavers when this Pokemon is enjoying itself. If the Pokémon becomes enraged, the flame burns fiercely.",
            "This Pokemon mercilessly destroys its foes using its sharp claws. If it encounters a strong foe, it turns aggressive. In this excited state, the flame at the tip of its tail flares with a bluish white color.",
            "This Pokemon flies around the sky in search of powerful opponents. It breathes fire of such great heat that it melts anything. However, it never turns its fiery breath on any opponent weaker than itself.",
            "This Pokemon's shell is not merely used for protection. The shell's rounded shape and the grooves on its surface help minimize resistance in water, enabling this Pokémon to swim at high speeds.",
            "Its tail is large and covered with a rich, thick fur. The tail becomes increasingly deeper in color as this Pokemon ages. The scratches on its shell are evidence of this Pokémon's toughness as a battler.",
            "This Pokemon has water spouts that protrude from its shell. The water spouts are very accurate. They can shoot bullets of water with enough accuracy to strike empty cans from a distance of over 160 feet.",
            "This Pokemon has a voracious appetite. It can devour leaves bigger than its body right before your eyes. From its antenna, this Pokémon releases a terrifically strong odor.",
            "The shell covering this Pokémon's body is as hard as an iron slab. This Pokemon does not move very much. It stays still because it is preparing its soft innards for evolution inside the hard shell.",
            "This Pokemon has a superior ability to search for delicious honey from flowers. It can even search out, extract, and carry honey from flowers that are blooming over six miles from its nest.",
            "This Pokemon has an extremely acute sense of smell. It is capable of distinguishing its favorite kinds of leaves from those it dislikes just by sniffing with its big red proboscis (nose).",
            "This Pokemon remains virtually immobile as it clings to a tree. However, on the inside, it is extremely busy as it prepares for its coming evolution. This is evident from how hot the shell becomes to the touch.",
            "This Pokemon is extremely territorial. No one should ever approach its nest - this is for their own safety. If angered, they will attack in a furious swarm.",
            "This Pokemon has an extremely sharp sense of direction. It is capable of unerringly returning home to its nest, however far it may be removed from its familiar surroundings.",
            "This Pokemon claims a large area as its own territory. This Pokémon flies around, patrolling its living space. If its territory is violated, it shows no mercy in thoroughly punishing the foe with its sharp claws.",
            "This Pokémon has a dazzling plumage of beautifully glossy feathers. Many Trainers are captivated by the striking beauty of the feathers on its head, compelling them to choose this Pokemon as their Pokémon.",
            "This Pokemon is cautious in the extreme. Even while it is asleep, it constantly listens by moving its ears around. It is not picky about where it lives - it will make its nest anywhere.",
            "This Pokemon's sturdy fangs grow steadily. To keep them ground down, it gnaws on rocks and logs. It may even chew on the walls of houses.",
            "This Pokemon has a very loud cry that can be heard over half a mile away. If its high, keening cry is heard echoing all around, it is a sign that they are warning each other of danger.",
            "This Pokemon is recognized by its long neck and elongated beak. They are conveniently shaped for catching prey in soil or water. It deftly moves its long and skinny beak to pluck prey.",
            "This Pokemon curls itself up in a spiral while it rests. Assuming this position allows it to quickly respond to a threat from any direction with a glare from its upraised head.",
            "This Pokémon is terrifically strong in order to constrict things with its body. It can even flatten steel oil drums. Once this Pokemon wraps its body around its foe, escaping its crunching embrace is impossible.",
            "Whenever this Pokemon comes across something new, it blasts it with a jolt of electricity. If you come across a blackened berry, it's evidence that this Pokémon mistook the intensity of its charge.",
            "If the electrical sacks become excessively charged, this Pokemon plants its tail in the ground and discharges. Scorched patches of ground will be found near this Pokémon's nest.",
            "This Pokemon's body is configured to absorb water without waste, enabling it to survive in an arid desert. This Pokémon curls up to protect itself from its enemies.",
            "This Pokemon's body is covered by tough spikes, which are hardened sections of its hide. Once a year, the old spikes fall out, to be replaced with new spikes that grow out from beneath the old ones.",
            "This Pokemon has barbs that secrete a powerful poison. They are thought to have developed as protection for this small-bodied Pokémon. When enraged, it releases a horrible toxin from its horn.",
            "When these Pokemon are with their friends or family, they keep their barbs tucked away to prevent hurting each other. This Pokémon appears to become nervous if separated from the others.",
            "This Pokémon's body is encased in extremely hard scales. It is adept at sending foes flying with harsh tackles. This Pokémon is at its strongest when it is defending its young.",
            "The males of this Pokemon has developed muscles for moving its ears. Thanks to them, the ears can be freely moved in any direction. Even the slightest sound does not escape this Pokémon's notice.",
            "This Pokemon has a horn that is harder than a diamond. If it senses a hostile presence, all the barbs on its back bristle up at once, and it challenges the foe with all its might.",
            "This Pokémon's thick tail packs enormously destructive power. With one swing, it can topple a metal transmission tower. Once this Pokémon goes on a rampage, there is no stopping it.",
            "On every night of a full moon, groups of this Pokémon come out to play. When dawn arrives, the tired Pokemon return to their quiet mountain retreats and go to sleep nestled up against each other.",
            "This Pokémon moves by skipping lightly as if it were flying using its wings. Its bouncy step lets it even walk on water. It is known to take strolls on lakes on quiet, moonlit nights.",
            "At the time of its birth, this Pokemon has one white tail. The tail separates into six if this Pokémon receives plenty of love from its Trainer. The six tails become magnificently curled.",
            "This Pokémon casts a sinister light from its bright red eyes to gain total control over its foe's mind. This Pokémon is said to live for a thousand years.",
            "This Pokemon's vocal chords can freely adjust the wavelength of its voice. This Pokémon uses this ability to sing at precisely the right wavelength to make its foes most drowsy.",
            "This Pokémon has large, saucerlike eyes. The surfaces of its eyes are always covered with a thin layer of tears. If any dust gets in this Pokémon's eyes, it is quickly washed away.",
            "This Pokemon remains quietly unmoving in a dark spot during the bright daylight hours. It does so because prolonged exposure to the sun causes its body to become slightly burned.",
            "This Pokémon loves to drink the blood of living things. It is particularly active in the pitch black of night. This Pokémon flits around in the night skies, seeking fresh blood.",
            "During the daytime, this Pokémon buries itself in soil to absorb nutrients from the ground using its entire body. The more fertile the soil, the glossier its leaves become.",
            "This Pokémon releases a foul fragrance from the pistil of its flower. When faced with danger, the stench worsens. If this Pokémon is feeling calm and secure, it does not release its usual stinky aroma.",
            "This Pokémon's toxic pollen triggers atrocious allergy attacks. That's why it is advisable never to approach any attractive flowers in a jungle, however pretty they may be.",
            "This Pokémon has parasitic tochukaso mushrooms growing on its back. They grow by drawing nutrients from the host. They are valued as a medicine for long life.",
            "This Pokémon is known to infest large trees en masse and drain nutrients from the lower trunk and roots. When an infested tree dies, they move onto another tree all at once.",
            "This Pokémon is said to have evolved with a coat of thin, stiff hair that covers its entire body for protection. It possesses large eyes that never fail to spot even minuscule prey.",
            "This Pokémon is nocturnal - it is a Pokémon that only becomes active at night. Its favorite prey are small insects that gather around streetlights, attracted by the light in the darkness.",
            "These Pokémon are raised in most farms. The reason is simple - wherever this Pokémon burrows, the soil is left perfectly tilled for planting crops. This soil is made ideal for growing delicious vegetables.",
            "These Pokémon are actually triplets that emerged from one body. As a result, each triplet thinks exactly like the other two triplets. They work cooperatively to burrow endlessly.",
            "This Pokémon withdraws its sharp claws into its paws to slinkily sneak about without making any incriminating footsteps. For some reason, this Pokémon loves shiny coins that glitter with light.",
            "This Pokemon has six bold whiskers that give it a look of toughness. The whiskers sense air movements to determine what is in the Pokémon's surrounding vicinity. It becomes docile if grabbed by the whiskers.",
            "This Pokémon uses a mysterious power. When it does so, this Pokémon generates brain waves that are supposedly only seen in sleepers. This discovery spurred controversy among scholars.",
            "The webbed flippers on its forelegs and hind legs and the streamlined body of this Pokemon give it frightening speed. This Pokémon is definitely much faster than even the most athletic swimmer.",
            "When this Pokémon starts shaking and its nasal breathing turns rough, it's a sure sign that it is becoming angry. However, because it goes into a towering rage almost instantly, it is impossible for anyone to flee its wrath.",
            "When this Pokemon becomes furious, its blood circulation is boosted. In turn, its muscles are made even stronger. However, it also becomes much less intelligent at the same time.",
            "This Pokémon has a superb sense of smell. Once it smells anything, this Pokémon won't forget the scent, no matter what. It uses its advanced olfactory sense to determine the emotions of other living things.",
            "This Pokemon is known for its high speed. It is said to be capable of running over 6,200 miles in a single day and night. The fire that blazes wildly within this Pokémon's body is its source of power.",
            "This Pokémon has a very thin skin. It is possible to see the Pokémon's spiral innards right through the skin. Despite its thinness, however, the skin is also very flexible. Even sharp fangs bounce right off it.",
            "The surface of this Pokémon's body is always wet and slick with an oily fluid. Because of this greasy covering, it can easily slip and slide out of the clutches of any enemy in battle.",
            "This Pokemon's highly developed, brawny muscles never grow fatigued, however much it exercises. It is so tirelessly strong, this Pokémon can swim back and forth across the Pacific Ocean without effort.",
            "This Pokémon sleeps for eighteen hours a day. However, it can sense the presence of foes even while it is sleeping. In such a situation, this Pokémon immediately teleports to safety.",
            "This Pokémon emits a peculiar alpha wave if it develops a headache. Only those people with a particularly strong psyche can hope to become a Trainer of this Pokémon.",
            "This Pokemon's brain continually grows, infinitely multiplying brain cells. This amazing brain gives this Pokémon an astoundingly high IQ of 5,000. It has a thorough memory of everything that has occurred in the world.",
            "This Pokémon's muscles are special - they never get sore no matter how much they are used in exercise. This Pokémon has sufficient power to hurl a hundred adult humans.",
            "This Pokémon's thoroughly toned muscles possess the hardness of steel. This Pokémon has so much strength, it can easily hold aloft a sumo wrestler on just one finger.",
            "This Pokemon has the power to hurl anything aside. However, trying to do any work requiring care and dexterity causes its arms to get tangled. This Pokémon tends to leap into action before it thinks.",
            "This Pokémon's thin and flexible body lets it bend and sway to avoid any attack, however strong it may be. From its mouth, it leaks a fluid that melts even iron.",
            "This Pokémon has a large hook on its rear end. At night, the Pokémon hooks on to a tree branch and goes to sleep. If it moves around in its sleep, it may wake up to find itself on the ground.",
            "This Pokemon has a long vine that extends from its head. This vine is waved and flicked about as if it were an animal to attract prey. When an unsuspecting prey draws near, this Pokémon swallows it whole.",
            "This Pokémon's body is largely composed of water. If it is removed from the sea, it dries up like parchment. If this Pokémon happens to become dehydrated, put it back into the sea.",
            "This Pokemon has large red orbs on its head. The orbs glow before lashing the vicinity with a harsh ultrasonic blast. This Pokémon's outburst causes rough waves around it.",
            "When this Pokémon sleeps deeply, it buries itself halfway into the ground. It will not awaken even if hikers step on it unwittingly. In the morning, this Pokémon rolls downhill in search of food.",
            "This Pokémon grows by feeding on rocks. Apparently, it prefers to eat rocks that are covered in moss. This Pokémon eats it way through a ton of rocks on a daily basis.",
            "These Pokemon live up on mountains. If there is a large earthquake, these Pokémon will come rolling down off the mountains en masse to the foothills below.",
            "This Pokémon is very weak at birth. It can barely stand up. This Pokémon becomes stronger by stumbling and falling to keep up with its parent.",
            "This Pokemon usually can be seen casually cantering in the fields and plains. However, when this Pokémon turns serious, its fiery manes flare and blaze as it gallops its way up to 150 mph.",
            "This Pokémon uses its tail to catch prey by dipping it in water at the side of a river. However, this Pokémon often forgets what it's doing and often spends entire days just loafing at water's edge.",
            "This Pokemon's tail has a Shellder firmly attached with a bite. As a result, the tail can't be used for fishing anymore. This causes this Pokemon to grudgingly swim and catch prey instead.",
            "This Pokémon attaches itself to power lines to feed on electricity. If your house has a power outage, check your circuit breakers. You may find a large number of this Pokémon clinging to the breaker box.",
            "This Pokemon emits a powerful magnetic force that is fatal to mechanical devices. As a result, large cities sound sirens to warn citizens of large-scale outbreaks of this Pokémon.",
            "This Pokemon is always seen with a stick from a plant of some sort. Apparently, there are good sticks and bad sticks. This Pokémon has been known to fight with others over sticks.",
            "This Pokémon's two heads never sleep at the same time. Its two heads take turns sleeping, so one head can always keep watch for enemies while the other one sleeps.",
            "Watch out if this Pokemon's three heads are looking in three separate directions. It's a sure sign that it is on its guard. Don't go near this Pokémon if it's being wary - it may decide to peck you.",
            "This Pokémon hunts for prey in the frigid sea underneath sheets of ice. When it needs to breathe, it punches a hole through the ice with the sharply protruding section of its head.",
            "This Pokemon loves to snooze on bitterly cold ice. The sight of this Pokémon sleeping on a glacier was mistakenly thought to be a mermaid by a mariner long ago.",
            "This Pokémon's sludgy and rubbery body can be forced through any opening, however small it may be. This Pokémon enters sewer pipes to drink filthy wastewater.",
            "From this Pokemon's body seeps a foul fluid that gives off a nose-bendingly horrible stench. Just one drop of this Pokémon's body fluid can turn a pool stagnant and rancid.",
            "At night, this Pokémon uses its broad tongue to burrow a hole in the seafloor sand and then sleep in it. While it is sleeping, this Pokémon closes its shell, but leaves its tongue hanging out.",
            "This Pokemon is capable of swimming in the sea. It does so by swallowing water, then jetting it out toward the rear. This Pokémon shoots spikes from its shell using the same system.",
            "This Pokémon is largely composed of gaseous matter. When exposed to a strong wind, the gaseous body quickly dwindles away. Groups of this Pokémon cluster under the eaves of houses to escape the ravages of wind.",
            "This Pokémon is a dangerous Pokémon. If one beckons you while floating in darkness, you must never approach it. This Pokémon will try to lick you with its tongue and steal your life away.",
            "Sometimes, on a dark night, your shadow thrown by a streetlight will suddenly and startlingly overtake you. It is actually this Pokémon running past you, pretending to be your shadow.",
            "This Pokémon has a magnet in its brain. It acts as a compass so that this Pokémon does not lose direction while it is tunneling. As it grows older, its body becomes increasingly rounder and smoother.",
            "If your nose becomes itchy while you are sleeping, it's a sure sign that this Pokemon is standing above your pillow and trying to eat your dream through your nostrils.",
            "This Pokémon holds a pendulum in its hand. The arcing movement and glitter of the pendulum lull the foe into a deep state of hypnosis. While this Pokémon searches for prey, it polishes the pendulum.",
            "These Pokemon live on beaches, burrowed inside holes dug into the sand. On sandy beaches with little in the way of food, these Pokémon can be seen squabbling with each other over territory.",
            "This Pokémon has an enormous, over sized claw. It waves this huge claw in the air to communicate with others. However, because the claw is so heavy, the Pokémon quickly tires.",
            "This Pokemon was first sighted at a company that manufactures Poké Balls. The link between that sighting and the fact that this Pokémon looks very similar to a Poké Ball remains a mystery.",
            "This Pokémon eats electricity in the atmosphere. On days when lightning strikes, you can see this Pokémon exploding all over the place from eating too much electricity.",
            "This Pokémon consists of six eggs that form a closely knit cluster. The six eggs attract each other and spin around. When cracks increasingly appear on the eggs, this Pokemon is close to evolution.",
            "This Pokémon originally came from the tropics. Its heads steadily grow larger from exposure to strong sunlight. It is said that when the heads fall off, they group together to form Exeggcute.",
            "This Pokemon pines for the mother it will never see again. Seeing a likeness of its mother in the full moon, it cries. The stains on the skull the Pokémon wears are made by the tears it sheds.",
            "This Pokémon is the evolved form of a Cubone that has overcome its sadness at the loss of its mother and grown tough. This Pokémon's tempered and hardened spirit is not easily broken.",
            "This Pokémon's legs freely contract and stretch. Using these springlike legs, it bowls over foes with devastating kicks. After battle, it rubs down its legs and loosens the muscles to overcome fatigue.",
            "This Pokémon is said to possess the spirit of a boxer who had been working towards a world championship. This Pokémon has an indomitable spirit and will never give up in the face of adversity.",
            "Whenever this Pokémon comes across something new, it will unfailingly give it a lick. It does so because it memorizes things by texture and by taste. It is somewhat put off by sour things.",
            "If this Pokemon becomes agitated, it raises the toxicity of its internal gases and then jets them out from all over its body. This Pokémon may overinflate its round body, then explode.",
            "This Pokémon loves the gases given off by rotted kitchen garbage. This Pokémon will find a dirty, unkempt house and make it its home. At night, when the people in the house are asleep, it will go through the trash.",
            "This Pokemon runs in a straight line, smashing everything in its path. It is not bothered even if it rushes headlong into a block of steel. This Pokémon may feel some pain from the collision the next day, however.",
            "This Pokémon's horn can crush even uncut diamonds. One sweeping blow of its tail can topple a building. This Pokémon's hide is extremely tough. Even direct cannon hits don't leave a scratch.",
            "This Pokémon lays nutritionally excellent eggs on an everyday basis. The eggs are so delicious, they are easily and eagerly devoured by even those people who have lost their appetite.",
            "This Pokémon's vines snap off easily if they are grabbed. This happens without pain, allowing it to make a quick getaway. The lost vines are replaced by newly grown vines the very next day.",
            "If you come across the young of this Pokemon playing by itself, you must never disturb it or attempt to catch it. The baby Pokémon's parent is sure to be in the area, and it will become violently enraged at you.",
            "This Pokemon eats small insects and moss off of rocks. If the ocean current turns fast, this Pokémon anchors itself by wrapping its tail around rocks or coral to prevent being washed away.",
            "This Pokémon sleeps after wriggling itself between the branches of coral. Those trying to harvest coral are occasionally stung by this Pokémon's poison barbs if they fail to notice it.",
            "This Pokemon is a very beautiful Pokémon with fins that billow elegantly in water. However, don't let your guard down around this Pokémon - it could ram you powerfully with its horn.",
            "In the autumn, males of this Pokémon can be seen performing courtship dances in riverbeds to woo females. During this season, this Pokémon's body coloration is at its most beautiful.",
            "This Pokemon's center section has an organ called the core that shines bright red. If you go to a beach toward the end of summer, the glowing cores of these Pokémon look like the stars in the sky.",
            "This Pokémon's center section - the core - glows brightly in seven colors. Because of its luminous nature, this Pokémon has been given the nickname 'the gem of the sea.'",
            "This Pokémon is a master of pantomime. Its gestures and motions convince watchers that something unseeable actually exists. Once it is believed, it will exist as if it were a real thing.",
            "This Pokémon is blindingly fast. Its blazing speed enhances the effectiveness of the twin scythes on its forearms. This Pokémon's scythes are so effective, they can slice through thick logs in one wicked stroke.",
            "This Pokémon walks rhythmically, swaying and shaking its hips as if it were dancing. Its motions are so bouncingly alluring, people seeing it are compelled to shake their hips without giving any thought to what they are doing.",
            "When a storm arrives, gangs of this Pokémon compete with each other to scale heights that are likely to be stricken by lightning bolts. Some towns use this Pokémon in place of lightning rods.",
            "In battle, this Pokémon blows out intensely hot flames from all over its body to intimidate its opponent. This Pokémon's fiery bursts create heat waves that ignite grass and trees in its surroundings.",
            "This Pokémon is astoundingly strong. It can grip a foe weighing twice its weight in its horns and easily lift it. This Pokémon's movements turn sluggish in cold places.",
            "This Pokémon is not satisfied unless it is rampaging at all times. If there is no opponent for this Pokémon to battle, it will charge at thick trees and knock them down to calm itself.",
            "This Pokemon is a pathetic excuse for a Pokémon that is only capable of flopping and splashing. This behavior prompted scientists to undertake research into it.",
            "When Magikarp evolves into this Pokémon, its brain cells undergo a structural transformation. It is said that this transformation is to blame for this Pokémon's wildly violent nature.",
            "People have driven this Pokémon almost to the point of extinction. In the evenings, this Pokémon is said to sing plaintively as it seeks what few others of its kind still remain.",
            "This Pokemon rearranges its cell structure to transform itself into other shapes. However, if it tries to transform itself into something by relying on its memory, this Pokémon manages to get details wrong.",
            "This Pokemon has an unstable genetic makeup that suddenly mutates due to the environment in which it lives. Radiation from various stones causes this Pokémon to evolve.",
            "This Pokemon underwent a spontaneous mutation and grew fins and gills that allow it to live underwater. This Pokémon has the ability to freely control water.",
            "This Pokemon's cells generate a low level of electricity. This power is amplified by the static electricity of its fur, enabling the Pokémon to drop thunderbolts. The bristling fur is made of electrically charged needles.",
            "This Pokemon's fluffy fur has a functional purpose - it releases heat into the air so that its body does not get excessively hot. This Pokémon's body temperature can rise to a maximum of 1,650 degrees F.",
            "This Pokémon is capable of reverting itself entirely back to program data and entering cyberspace. This Pokémon is copy-protected so it cannot be duplicated by copying.",
            "This Pokemon is one of the ancient and long-since-extinct Pokémon that have been regenerated from fossils by people. If attacked by an enemy, it withdraws itself inside its hard shell.",
            "This Pokémon uses its tentacles to capture its prey. It is believed to have become extinct because its shell grew too large and heavy, causing its movements to become too slow and ponderous.",
            "This Pokemon is a Pokémon that has been regenerated from a fossil. However, in extremely rare cases, living examples have been discovered. The Pokémon has not changed at all for 300 million years.",
            "This Pokémon swam underwater to hunt for its prey in ancient times. The Pokémon was apparently evolving from being a water-dweller to living on land as evident from the beginnings of change in its gills and legs.",
            "This Pokémon is a Pokémon from the age of dinosaurs. It was regenerated from genetic material extracted from amber. It is imagined to have been the king of the skies in ancient times.",
            "This Pokémon's typical day consists of nothing more than eating and sleeping. It is such a docile Pokémon that there are children who use its expansive belly as a place to play.",
            "This Pokemon is a legendary bird Pokémon that can control ice. The flapping of its wings chills the air. As a result, it is said that when this Pokémon flies, snow will fall.",
            "This Pokemon is a legendary bird Pokémon that has the ability to control electricity. It usually lives in thunderclouds. The Pokémon gains power if it is stricken by lightning bolts.",
            "This Pokemon is a legendary bird Pokémon that has the ability to control fire. If this Pokémon is injured, it is said to dip its body in the molten magma of a volcano to burn and heal itself.",
            "This Pokemon continually molts and sloughs off its old skin. It does so because the life energy within its body steadily builds to reach uncontrollable levels.",
            "This Pokemon stores an enormous amount of energy inside its body. It is said to alter weather conditions in its vicinity by discharging energy from the crystals on its neck and tail.",
            "This Pokémon is capable of circling the globe in just sixteen hours. It is a kindhearted Pokémon that leads lost and foundering ships in a storm to the safety of land.",
            "This Pokemon is a Pokémon that was created by genetic manipulation. However, even though the scientific power of humans created this Pokémon's body, they failed to endow it with a compassionate heart.",
            "This Pokemon is said to possess the genetic composition of all Pokémon. It is capable of making itself invisible at will, so it entirely avoids notice even if it approaches people."


    };

    public static String[] DexEntryAnswers = {

            "Bulbasaur",
            "Ivysaur",
            "Venusaur",
            "Charmander",
            "Charmeleon",
            "Charizard",
            "Squirtle",
            "Wartortle",
            "Blastoise",
            "Caterpie",
            "Metapod",
            "Butterfree",
            "Weedle",
            "Kakuna",
            "Beedrill",
            "Pidgey",
            "Pidgeotto",
            "Pidgeot",
            "Rattata",
            "Raticate",
            "Spearow",
            "Fearow",
            "Ekans",
            "Arbok",
            "Pikachu",
            "Raichu",
            "Sandshrew",
            "Sandslash",
            "Nidoran",
            "Nidorina",
            "Nidoqueen",
            "Nidoran",
            "Nidorino",
            "Nidoking",
            "Clefairy",
            "Clefable",
            "Vulpix",
            "Ninetales",
            "Jigglypuff",
            "Wigglytuff",
            "Zubat",
            "Golbat",
            "Oddish",
            "Gloom",
            "Vileplume",
            "Paras",
            "Parasect",
            "Venonat",
            "Venemoth",
            "Diglett",
            "Dugtrio",
            "Meowth",
            "Persian",
            "Psyduck",
            "Golduck",
            "Mankey",
            "Primeape",
            "Growlithe",
            "Arcanine",
            "Poliwag",
            "Poliwhirl",
            "Poliwrath",
            "Abra",
            "Kadabra",
            "Alakazam",
            "Machop",
            "Machoke",
            "Machamp",
            "Bellsprout",
            "Weepinbell",
            "Victreebel",
            "Tentacool",
            "Tentacruel",
            "Geodude",
            "Graveler",
            "Golem",
            "Ponyta",
            "Rapidash",
            "Slowpoke",
            "Slowbro",
            "Magnemite",
            "Magneton",
            "Farfetch'd",
            "Doduo",
            "Dodrio",
            "Seel",
            "Dewgong",
            "Grimer",
            "Muk",
            "Shellder",
            "Cloyster",
            "Gastly",
            "Haunter",
            "Gengar",
            "Onix",
            "Drowzee",
            "Hypno",
            "Krabby",
            "Kingler",
            "Voltorb",
            "Electrode",
            "Exeggcute",
            "Exeggutor",
            "Cubone",
            "Marowak",
            "Hitmonlee",
            "Hitmonchan",
            "Lickitung",
            "Koffing",
            "Weezing",
            "Rhyhorn",
            "Rhydon",
            "Chansey",
            "Tangela",
            "Kangaskhan",
            "Horsea",
            "Seadra",
            "Goldeen",
            "Seaking",
            "Staryu",
            "Starmie",
            "Mr. Mime",
            "Scyther",
            "Jynx",
            "Electabuzz",
            "Magmar",
            "Pinsir",
            "Tauros",
            "Magikarp",
            "Gyarados",
            "Lapras",
            "Ditto",
            "Eevee",
            "Vaporeon",
            "Jolteon",
            "Flareon",
            "Porygon",
            "Omanyte",
            "Omastar",
            "Kabuto",
            "Kabutops",
            "Aerodactyl",
            "Snorlax",
            "Articuno",
            "Zapdos",
            "Moltres",
            "Dratini",
            "Dragonair",
            "Dragonite",
            "Mewtwo",
            "Mew"



    };
}
